# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
    - master

pool:
    vmImage: "windows-latest"

variables:
    solution: "**/*.sln"
    buildPlatform: "Any CPU"
    buildConfiguration: "Release"

steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: sdk
        version: 3.x
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: NuGetToolInstaller@0

    - task: DotNetCoreCLI@2
      inputs:
        command: restore
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      inputs:
        command: build
        projects: '**/*.csproj'

    - task: VSTest@2
      inputs:
          platform: "$(buildPlatform)"
          configuration: "$(buildConfiguration)"
